### PR TITLE
Add usage example to Web.Storage.Storage. Closes #5.

### LINKED ISSUE #5: Type signature confusion, too many strings
Good morning,

I become confused when I read the documentation on [Pursuit](https://pursuit.purescript.org/packages/purescript-web-storage/2.0.0/docs/Web.Storage.Storage), since many of the parameters to the functions are strings. 

I have two proposed solutions to my confusion:

- Either: add type aliases for the key and value parameters
- Or: add a description for each relevant function that describes what each parameter does.

I can make a pull request if you think this is a good idea.

What do you think?

### PR DESCRIPTION
**Pull request by Rembane**

### CODE REVIEW

**Comment by Rembane** [comment]
It seems like I also took the liberty to add more newlines in the doc strings. The joy of resuming work on an old clone and not really paying attention.

**Comment by hdgarrood** [comment]
Looks great, but I think it's worth adding imports, as otherwise it might not be completely clear where `localStorage` and `window` are coming from.

**Comment by Rembane** [comment]
Sure thing! Imports added.

**Review by hdgarrood — APPROVED** [review]
Thanks!

**Pull request merged**
